### ISSUE TITLE
Running the Game

### ISSUE THREAD

**Issue by jallen3095** [kkmoslehpour/Android-multiplayer-tic-tac-toe-socket.io-#1]
Hello,

I am interested in learning Socket.io with Android and I came across your repo. Could you help me get everything running? I started up the server on port 3000 and started the game on an emulator. But I am having trouble getting two devices connected. It would be greatly appreciated if you could help me get your program running so I can see how this all works!

Thank you!

**Comment by kkmoslehpour** [comment]
@jallen3095 Sure, one thing to note is that you have to change the following IP `IO.socket("http://192.168.1.67:3000");` to your own computers IP. Then you would have to fire up two emulators and you should see it work. Let me know if you still have issues.

**Comment by jallen3095** [comment]
Hi, thank you so much! That solved the problem! I was putting localhost:3000 instead of my IP. Thank you again for your reply.
